---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx-phpfpm
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-phpfpm
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      volumes:
        - name: shared-files
          configMap:
            name: nginx-config
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx-container
          image: nginx:1.22
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html/index.php
              subPath: index.php
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: php-fpm-container
          image: php:7.0-fpm
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
...

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm
  namespace: nginx
  labels:
    app: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...